"""
auth.py — Session + WhatsApp magic-link authentication for LUKA Frontend.

Real users log in via a one-time link the WhatsApp bot sends in response to
`/link` (see `DashboardLinkService` in the `luka` repo): the token is hashed
and looked up against `dashboard_login_link`, consumed on first use, and
resolves to the linked `Usuario` — identified by `auth_user_id`, never a
mock id. `/dev-login` remains a local-only shortcut gated by
`mock_auth_enabled()` for developing without the bot running.
"""

import hashlib
import os
from datetime import datetime, timezone
from typing import Optional

from dotenv import load_dotenv
from fastapi import HTTPException, Request, status
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer
from sqlalchemy.orm import Session

from app.models.database import DashboardLoginLink, Usuario
from app.services.supabase_auth import _secret_key

load_dotenv()

# --- Configuration -----------------------------------------------------------
MOCK_AUTH_USER_ID = os.getenv(
    "MOCK_AUTH_USER_ID", "00000000-0000-0000-0000-000000000001"
)
SESSION_COOKIE = "luka_session"
SESSION_MAX_AGE = 60 * 60 * 24 * 7  # 7 days


def mock_auth_enabled() -> bool:
    """Keep development shortcuts unavailable outside explicit mock mode."""
    app_env = os.getenv("APP_ENV", "development").strip().lower()
    enabled = os.getenv("ENABLE_MOCK_AUTH", "true").strip().lower() == "true"
    return app_env == "development" and enabled


def _serializer() -> URLSafeTimedSerializer:
    # Reuses the same production-guarded SECRET_KEY as the Supabase/onboarding
    # cookies (app.services.supabase_auth._secret_key) — no separate insecure
    # hardcoded fallback for the dashboard session.
    return URLSafeTimedSerializer(_secret_key())


# --- Session helpers ----------------------------------------------------------


def create_session_token(auth_user_id: str) -> str:
    """Sign an auth_user_id into a tamper-proof session cookie value."""
    return _serializer().dumps(auth_user_id, salt="session")


def decode_session_token(token: str) -> Optional[str]:
    """Return the auth_user_id or None if invalid/expired."""
    try:
        return _serializer().loads(token, salt="session", max_age=SESSION_MAX_AGE)
    except (BadSignature, SignatureExpired):
        return None


# --- WhatsApp magic link (real, single-use) -----------------------------------


def consume_dashboard_login_token(token: str, db: Session) -> Optional[str]:
    """
    Verify a dashboard login token generated by the bot's DashboardLinkService
    (luka) and, on success, atomically mark it consumed so it can't be reused.

    Takes the caller's request-scoped `db` session (same convention as
    `validate_registration_token`) instead of opening its own — this is what
    lets FastAPI's `get_db` override apply consistently, including in tests.

    Returns the linked user's auth_user_id, or None if the token is
    missing/unknown/expired/already used/unlinked. Never distinguishes these
    cases in the return value — callers must not infer which one occurred.
    """
    if not isinstance(token, str) or not token:
        return None

    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    try:
        link = (
            db.query(DashboardLoginLink)
            .filter(DashboardLoginLink.token_hash == token_hash)
            .with_for_update()
            .first()
        )
        if link is None or link.estado != "pendiente":
            return None

        expira_en = link.expira_en
        if expira_en.tzinfo is None:
            expira_en = expira_en.replace(tzinfo=timezone.utc)
        if expira_en <= datetime.now(timezone.utc):
            link.estado = "vencido"
            db.commit()
            return None

        user = db.query(Usuario).filter(Usuario.id == link.usuario_id).first()
        if user is None or user.auth_user_id is None:
            return None

        link.estado = "consumido"
        link.consumido_en = datetime.now(timezone.utc)
        auth_user_id = str(user.auth_user_id)
        db.commit()
        return auth_user_id
    except Exception:
        db.rollback()
        return None


# --- FastAPI dependency -------------------------------------------------------


def get_current_user(request: Request) -> str:
    """
    Dependency: read the session cookie and return the auth_user_id.
    Raises 401 if missing or invalid — caller should redirect to /login.
    """
    raw = request.cookies.get(SESSION_COOKIE)
    if not raw:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated",
        )
    auth_user_id = decode_session_token(raw)
    if not auth_user_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Session expired",
        )
    return auth_user_id
